version: '3.8'
services:
  database:
    image: postgres:latest
    networks:
        - app-network
    container_name: database_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: invest_master
    volumes:
      - ./database:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend_container
    networks:
      - app-network
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - DOTNET_WATCH=true
    command: ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:5000"]

  frontend:
   build: ./frontend
   container_name: frontend_container
   ports:
      - "3000:3000"
   stdin_open: true
   tty: true
   networks:
    - app-network
   volumes:
    - ./frontend:/app
    - /app/node_modules
   environment:
    - WATCHPACK_POLLING=true

  



networks:
  app-network:
    driver: bridge
